---
apiVersion: tekton.dev/v1beta1
kind: Pipelinerun
metadata:
  name: pipeline-status
  labels:
    app.kubernetes.io/version: "0.1"
spec:
  params:
    - name: repo_url
      default: "https://github.com/manojbison/pipeline-status.git"
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.repo_url)
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: source
  finally:
    - name: notify-any-failure
      when:
        - input: $(tasks.status)
          operator: in
          values: ["Failed"]
      taskRef:
        name: send-to-slack-channel
      params:
        - name: webhook-secret
          value: slack
        - name: message
          value: "Hello from Tekton!"
        - name: icon-emoji
          value: ':Failed:'
      # - name: notify-any-failure
      #   when:
      #     - input: $(tasks.status)
      #       operator: in
      #       values: ["Failed"]
      #   taskRef:
      #     name: send-mail
      #   params:
      #     - name: webhook-secret
      #       value: webhook-secret
      #     - name: message
      #       value: "Hello from Tekton!"
  workspaces:
  - name: source
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
